# NOTE version is important for mem_limit, no swarm
version: "2"
name: "remix3-default"
services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres

    container_name: "remix3-pg"
    env_file: ./.env
    tty: true # Enables debugging capabilities when attached to this container.
    # stdin_open: true
    ports:
      - 5452:5452
    volumes:
      - ../.data/pg:/var/lib/postgresql/data

  web:
    mem_limit: ${WEB_MEM_LIMIT}
    # environment:
    #   - CURRENT_GUID=${CURRENT_GUID}
    #   - CURRENT_UID=${CURRENT_UID}

    build:
      context: .
      dockerfile: ./Dockerfile.nodejs
      args:
        CURRENT_GUID: ${CURRENT_GUID}
        CURRENT_UID: ${CURRENT_UID}
    container_name: "remix3-http"
    tty: true # Enables debugging capabilities when attached to this container.
    # run as me
    # get the ids like this:
    # export CURRENT_UID_GID=$(id -u):$(id -g)
    # user: ${CURRENT_UID}:${CURRENT_GUID}

    depends_on:
      - db
    links:
      - db
    command: sh -c '${WEB_CMD}'
    ports:      
      - 3200:3200
      - 5173:5173
    volumes:
      - ../:/app
      - /tmp/rp-web-tmp/:/tmp
      - /tmp/rp-web-cache/:/home/tudor/.cache
