FROM postgres:12.16
ENV DEBIAN_FRONTEND noninteractive

#TODO make this into a script for both pg and node
RUN apt-get update && apt-get install -y iputils-ping \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

#custom port so we don-t clash with the host
CMD ["-p", "5452"]

